# -*- coding: utf-8 -*-
"""Denitrification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-5QqFTlOCAmlrMQcj8aVYLzzVX7VAB1
"""

'''Variability of Marine Denitrification in the Southern Arabian Sea Over the Last ~167 ka'''

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the file
file = "1_SSD004_GC11_nitrogen.tab"

df = pd.read_csv(
    file,
    sep="\t",
    comment="/",
    skiprows=21
)

# See the columns
print(df.columns)

# First 5 rows
print(df.head())

# d15N vs Age

plt.figure(figsize=(12, 6))

plt.plot(
    df["Age [ka BP]"],
    df["δ15N bulk [‰ air]"],
    linewidth=1
)

plt.scatter(
    df["Age [ka BP]"],
    df["δ15N bulk [‰ air]"],
    s=10,
    alpha=0.5
)

plt.xlabel("Age (ka BP)")
plt.ylabel(r"$\delta^{15}$N (‰ air)")
plt.title(r"$\delta^{15}$N variation through time")

plt.gca().invert_xaxis()

plt.grid(alpha=0.3)
plt.savefig("d15N variation with time")
plt.show()

# d15N vs TN

plt.figure(figsize=(8, 6))

plt.scatter(
    df["TN [%]"],
    df["δ15N bulk [‰ air]"],
    s=20,
    alpha=0.6
)

plt.xlabel("Total Nitrogen (TN, %)")
plt.ylabel(r"$\delta^{15}$N (‰ air)")
plt.title(r"$\delta^{15}$N vs Total Nitrogen")

plt.grid(alpha=0.3)

plt.show()

# calculating the correlation

correlation = df[
    ["TN [%]", "δ15N bulk [‰ air]"]
].corr()

print(correlation)

# Break MIS 5 apart
def MIS5_substage(age):

    if 115 <= age <= 130:
        return "MIS 5e"

    elif 105 <= age < 115:
        return "MIS 5d"

    elif 95 <= age < 105:
        return "MIS 5c"

    elif 85 <= age < 95:
        return "MIS 5b"

    elif 71 <= age < 85:
        return "MIS 5a"

    else:
        return None


df["MIS5_substage"] = df["Age [ka BP]"].apply(MIS5_substage)

mis5 = df.dropna(subset=["MIS5_substage"])

print(
    mis5.groupby("MIS5_substage")["δ15N bulk [‰ air]"]
       .agg(["count", "mean", "median", "std"])
)

# d15N variability through MIS intervals
import pandas as pd
import matplotlib.pyplot as plt


# 1. Load dataset
file = "1_SSD004_GC11_nitrogen.tab"

df = pd.read_csv(
    file,
    sep="\t",
    comment="/",
    skiprows=21
)

# Convert to numeric
df["Age [ka BP]"] = pd.to_numeric(
    df["Age [ka BP]"], errors="coerce"
)

df["δ15N bulk [‰ air]"] = pd.to_numeric(
    df["δ15N bulk [‰ air]"], errors="coerce"
)

# Remove missing values
df = df.dropna(
    subset=["Age [ka BP]", "δ15N bulk [‰ air]"]
)

# Sort by age
df = df.sort_values("Age [ka BP]")



# 2. Define MIS intervals
mis_intervals = [

    # Age start, age end, label, climate
    (0, 14.7, "MIS 1", "warm"),

    (14.7, 29, "MIS 2", "cold"),

    (29, 57, "MIS 3", "interstadial"),

    (57, 71, "MIS 4", "cold"),

    # MIS 5 substages
    (71, 85, "MIS 5a", "warm"),
    (85, 95, "MIS 5b", "cold"),
    (95, 105, "MIS 5c", "warm"),
    (105, 115, "MIS 5d", "cold"),
    (115, 130, "MIS 5e", "warm"),

    (130, 167.3, "MIS 6", "cold")
]



# 3. Plot δ15N
fig, ax = plt.subplots(figsize=(15, 7))



# 4. Add MIS background
for start, end, label, climate in mis_intervals:

    # Different shading strength for warm/cold
    if climate == "cold":
        alpha = 0.18
    elif climate == "warm":
        alpha = 0.07
    else:
        alpha = 0.04

    ax.axvspan(
        start,
        end,
        alpha=alpha
    )

    # MIS label
    midpoint = (start + end) / 2

    ax.text(
        midpoint,
        8.65,
        label,
        ha="center",
        va="top",
        fontsize=9,
        fontweight="bold"
    )



# 5. Plot δ15N record
ax.plot(
    df["Age [ka BP]"],
    df["δ15N bulk [‰ air]"],
    linewidth=1.2
)

ax.scatter(
    df["Age [ka BP]"],
    df["δ15N bulk [‰ air]"],
    s=9,
    alpha=0.4
)


# 6. Labels
ax.set_xlabel(
    "Age (ka BP)",
    fontsize=12
)

ax.set_ylabel(
    r"$\delta^{15}$N (‰ air)",
    fontsize=12
)

ax.set_title(
    r"$\delta^{15}$N Variability Through MIS 1–6",
    fontsize=14
)

# Older → younger
# 167 ka on left, present on right
ax.invert_xaxis()

ax.set_ylim(4.5, 9)

ax.grid(
    alpha=0.25
)

plt.tight_layout()
plt.savefig("d15N variability through MIS intervals")
plt.show()

# Assign each sample to its MIS

def assign_MIS(age):

    if age < 14.7:
        return "MIS 1"

    elif age < 29:
        return "MIS 2"

    elif age < 57:
        return "MIS 3"

    elif age < 71:
        return "MIS 4"

    elif age < 130:
        return "MIS 5"

    elif age <= 167.3:
        return "MIS 6"

    else:
        return None


df["MIS"] = df["Age [ka BP]"].apply(assign_MIS)

print(df[["Age [ka BP]", "δ15N bulk [‰ air]", "MIS"]].head(20))

# Calculate mean δ¹⁵N for each MIS
mis_summary = (
    df
    .groupby("MIS")["δ15N bulk [‰ air]"]
    .agg(
        ["count", "mean", "median", "std", "min", "max"]
    )
)

print(mis_summary)

# compare warm vs cold
warm_MIS = ["MIS 1", "MIS 3", "MIS 5"]
cold_MIS = ["MIS 2", "MIS 4", "MIS 6"]

df["Climate"] = df["MIS"].apply(
    lambda x:
        "Warm" if x in warm_MIS
        else "Cold" if x in cold_MIS
        else None
)

print(
    df.groupby("Climate")["δ15N bulk [‰ air]"]
      .agg(["count", "mean", "median", "std"])
)